# job build imge push to ghcr.io
# job build imge push to ghcr.io
name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    branches: -main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: .

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/angielink0/prometheus-marathon:latest .

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/angielink0/prometheus-marathon:latest # змінено на `tags` замість `tag`
# Path: .github/workflows/cicd.yaml
#update
